# Generated by Django 5.2.14 on 2026-05-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_alter_league_id_alter_membership_id_alter_perk_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='True when the season has concluded. League becomes read-only.'),
        ),
    ]
