# Generated by Django 5.2.14 on 2026-05-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castaways', '0003_castaway_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='castaway',
            name='original_tribe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='castaway',
            name='tribe_color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='castaway',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='season',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
