# Generated by Django 5.2.14 on 2026-05-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castaways', '0004_castaway_original_tribe_castaway_tribe_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='allows_new_leagues',
            field=models.BooleanField(default=True, help_text='False after leagues are archived; prevents new league creation during the dormant period.'),
        ),
        migrations.AddField(
            model_name='season',
            name='next_complete_notified_at',
            field=models.DateTimeField(blank=True, help_text='Set when the "cast complete" notification has been sent.', null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='next_detected_at',
            field=models.DateTimeField(blank=True, help_text='Set when castaways for season_number+1 first appear in the survivoR dataset.', null=True),
        ),
    ]
