# Generated by Django 5.2.14 on 2026-05-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castaways', '0005_season_allows_new_leagues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='castaway',
            name='alias',
            field=models.CharField(blank=True, default='', help_text='Display name override used site-wide and for Fandom image lookups. Leave blank to use the dataset name.', max_length=255),
        ),
    ]
